apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codl-ingress
  namespace: codl
spec:
  rules:
    - host: www.codl.nl
      http:
        paths:
          - backend:
              serviceName: codl-service
              servicePort: 80
            path: /
